---
name: "tag-Release"

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Set release name"
        run: |
          export RELEASE_NAME="${{ github.event.repository.name }}-dev"
          echo "::set-env name=NAME::$RELEASE_NAME"
        
      - name: "Build"
        if: success()
        run: |
            cd $GITHUB_WORKSPACE
            python makepackage.py

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/*
